[package]
name = "cli"
version = "0.1.0"
authors = ["LeRoyce Pearson <leroycepearson@geemili.xyz>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
structopt = "0.2"
directories = "1.0"
