[package]
name = "time-tracker"
version = "0.1.0"
authors = ["LeRoyce Pearson <leroycepearson@geemili.xyz>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
structopt = "0.2"
directories = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
toml = "0.5"
snafu = "0.4"
